import { type EventSubChannelChatAnnouncementNotificationEvent } from './EventSubChannelChatAnnouncementNotificationEvent';
import { type EventSubChannelChatBitsBadgeTierNotificationEvent } from './EventSubChannelChatBitsBadgeTierNotificationEvent';
import { type EventSubChannelChatCharityDonationNotificationEvent } from './EventSubChannelChatCharityDonationNotificationEvent';
import { type EventSubChannelChatCommunitySubGiftNotificationEvent } from './EventSubChannelChatCommunitySubGiftNotificationEvent';
import { type EventSubChannelChatGiftPaidUpgradeNotificationEvent } from './EventSubChannelChatGiftPaidUpgradeNotificationEvent';
import { type EventSubChannelChatPayItForwardNotificationEvent } from './EventSubChannelChatPayItForwardNotificationEvent';
import { type EventSubChannelChatPrimePaidUpgradeNotificationEvent } from './EventSubChannelChatPrimePaidUpgradeNotificationEvent';
import { type EventSubChannelChatRaidNotificationEvent } from './EventSubChannelChatRaidNotificationEvent';
import { type EventSubChannelChatResubNotificationEvent } from './EventSubChannelChatResubNotificationEvent';
import { type EventSubChannelChatSubGiftNotificationEvent } from './EventSubChannelChatSubGiftNotificationEvent';
import { type EventSubChannelChatSubNotificationEvent } from './EventSubChannelChatSubNotificationEvent';
import { type EventSubChannelChatUnraidNotificationEvent } from './EventSubChannelChatUnraidNotificationEvent';
import { type EventSubChannelChatSharedChatPayItForwardNotificationEvent } from './EventSubChannelChatSharedChatPayItForwardNotificationEvent';
import { type EventSubChannelChatSharedChatSubNotificationEvent } from './EventSubChannelChatSharedChatSubNotificationEvent';
import { type EventSubChannelChatSharedChatResubNotificationEvent } from './EventSubChannelChatSharedChatResubNotificationEvent';
import { type EventSubChannelChatSharedChatSubGiftNotificationEvent } from './EventSubChannelChatSharedChatSubGiftNotificationEvent';
import { type EventSubChannelChatSharedChatCommunitySubGiftNotificationEvent } from './EventSubChannelChatSharedChatCommunitySubGiftNotificationEvent';
import { type EventSubChannelChatSharedChatGiftPaidUpgradeNotificationEvent } from './EventSubChannelChatSharedChatGiftPaidUpgradeNotificationEvent';
import { type EventSubChannelChatSharedChatPrimePaidUpgradeNotificationEvent } from './EventSubChannelChatSharedChatPrimePaidUpgradeNotificationEvent';
import { type EventSubChannelChatSharedChatRaidNotificationEvent } from './EventSubChannelChatSharedChatRaidNotificationEvent';
import { type EventSubChannelChatSharedChatAnnouncementNotificationEvent } from './EventSubChannelChatSharedChatAnnouncementNotificationEvent';

export type EventSubChannelChatNotificationEvent =
	| EventSubChannelChatSubNotificationEvent
	| EventSubChannelChatResubNotificationEvent
	| EventSubChannelChatSubGiftNotificationEvent
	| EventSubChannelChatCommunitySubGiftNotificationEvent
	| EventSubChannelChatGiftPaidUpgradeNotificationEvent
	| EventSubChannelChatPrimePaidUpgradeNotificationEvent
	| EventSubChannelChatRaidNotificationEvent
	| EventSubChannelChatUnraidNotificationEvent
	| EventSubChannelChatPayItForwardNotificationEvent
	| EventSubChannelChatAnnouncementNotificationEvent
	| EventSubChannelChatCharityDonationNotificationEvent
	| EventSubChannelChatBitsBadgeTierNotificationEvent
	| EventSubChannelChatSharedChatSubNotificationEvent
	| EventSubChannelChatSharedChatResubNotificationEvent
	| EventSubChannelChatSharedChatSubGiftNotificationEvent
	| EventSubChannelChatSharedChatCommunitySubGiftNotificationEvent
	| EventSubChannelChatSharedChatGiftPaidUpgradeNotificationEvent
	| EventSubChannelChatSharedChatPrimePaidUpgradeNotificationEvent
	| EventSubChannelChatSharedChatPayItForwardNotificationEvent
	| EventSubChannelChatSharedChatRaidNotificationEvent
	| EventSubChannelChatSharedChatAnnouncementNotificationEvent;
